import img_staff_1 from "../assets/personnels/profile-1662145431.png";
import img_staff_2 from "../assets/personnels/profile-1662145355.png";
import img_staff_3 from "../assets/personnels/profile-1662144696.png";
import img_staff_4 from "../assets/personnels/profile-1662144567.png";
import img_staff_5 from "../assets/personnels/profile-1662144448.png";
let staffs = [
  {
    id: "5",
    citizen_id: "3500200687956",
    name_title: "นาง",
    name_th: "ปราณี กันธิมา",
    name_en: "Pranee Kanthima",
    position_academic: "เจ้าหน้าที่บริหารงานทั่วไป",
    position_manager: null,
    image_profile: img_staff_1,
    email: "pranee@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 11-12",
    education: "ศศ.บ.(การจัดการทั่วไป) สหวิทยาลัยล้านนาเชียงใหม่",
    personnel_type: "เจ้าหน้าที่",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "6",
    citizen_id: "3501400608970",
    name_title: "นาย",
    name_th: "ประทีป สุขสมัย",
    name_en: "Prateep Sooksamai",
    position_academic: "นักวิชาการโสตทัศนศึกษา",
    position_manager: null,
    image_profile: img_staff_2,
    email: "prateep@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 25",
    education: "วทบ.(เทคโนโลยีอุตสาหกรรม) มหาวิทยาลัยราชภัฎเชียงใหม่",
    personnel_type: "เจ้าหน้าที่",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "18",
    citizen_id: "3570700560521",
    name_title: "นางสาว",
    name_th: "พัชรี ยางยืน",
    name_en: "Phatcharee Yangyuen",
    position_academic: "นักวิชาการคอมพิวเตอร์ชำนาญการ",
    position_manager: null,
    image_profile: img_staff_3,
    email: "patcha.y@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 22",
    education: "วทม.(เทคโนโลยีสารสนเทศและการจัดการ)มหาวิทยาลัยเชียงใหม่",
    personnel_type: "เจ้าหน้าที่",
    academic_type: "ข้าราชการ",
  },
  {
    id: "19",
    citizen_id: "3509900691270",
    name_title: "นางสาว",
    name_th: "สุภาพรรณ อนุตรกุล",
    name_en: "Suphaphan Anuttarakun",
    position_academic: "นักวิชาการคอมพิวเตอร์",
    position_manager: null,
    image_profile: img_staff_4,
    email: "supapun@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 23",
    education: "วทม.(เทคโนโลยีสารสนเทศและการจัดการ) มหาวิทยาลัยเชียงใหม่",
    personnel_type: "เจ้าหน้าที่",
    academic_type: "ข้าราชการ",
  },
  {
    id: "20",
    citizen_id: "3660800333836",
    name_title: "นางสาว",
    name_th: "ช่อทิพย์ สิทธิ",
    name_en: "Chorthip Sitti",
    position_academic: "นักวิชาการคอมพิวเตอร์",
    position_manager: null,
    image_profile: img_staff_5,
    email: "chorthip_s@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 25",
    education: "วทม.(เทคโนโลยีสารสนเทศและการจัดการ) มหาวิทยาลัยเชียงใหม่",
    personnel_type: "เจ้าหน้าที่",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
];

export default staffs;
