import img_teacher_1 from "@/assets/personnels/profile-1662145520.png";
import img_teacher_2 from "@/assets/personnels/profile-1662145252.png";
import img_teacher_3 from "@/assets/personnels/profile-1662145176.png";
import img_teacher_4 from "@/assets/personnels/profile-1662145085.png";
import img_teacher_5 from "@/assets/personnels/profile-1662144987.png";
import img_teacher_6 from "@/assets/personnels/profile-1662144873.png";
import img_teacher_7 from "@/assets/personnels/profile-1662144788.png";
import img_teacher_8 from "@/assets/personnels/profile-1662144183.png";
import img_teacher_9 from "@/assets/personnels/profile-1662144056.png";
import img_teacher_10 from "@/assets/personnels/profile-1662143934.png";
import img_teacher_11 from "@/assets/personnels/profile-1662143796.png";
import img_teacher_12 from "@/assets/personnels/profile-1662143257.png";

let teachers = [
  {
    id: "3",
    citizen_id: "3500500417695",
    name_title: "อ.ดร.",
    name_th: "สมนึก สินธุปวน",
    name_en: "Somnuek Sinthupuan",
    position_academic: "อาจารย์",
    position_manager: null,
    image_profile: img_teacher_1,
    email: "somnuk@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 24",
    education:
      "ปร.ด.(วิทยาการคอมพิวเตอร์) หลักสูตรนานาชาติ สถาบันบัณฑิตพัฒนบริหารศาสตร์",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "8",
    citizen_id: "3660800333798",
    name_title: "ผศ.ดร.",
    name_th: "สนิท สิทธิ",
    name_en: "Snit Sitti",
    position_academic: "ผู้ช่วยศาสตราจารย์",
    position_manager: "ผู้อำนวยการสำนักบริหารและพัฒนาวิชาการ",
    image_profile: img_teacher_2,
    email: "snit@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 15",
    education: "ศษ.ด.(เทคโนโลยีการศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
    personnel_type: "อาจารย์",
    academic_type: "ข้าราชการ",
  },
  {
    id: "9",
    citizen_id: "3589900025130",
    name_title: "ผศ.",
    name_th: "ก่องกาญจน์ ดุลยไชย",
    name_en: "Kongkarn Dullayachai",
    position_academic: "ผู้ช่วยศาสตราจารย์",
    position_manager:
      "เลขานุการหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
    image_profile: img_teacher_3,
    email: "kongkarn@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 14",
    education: "วท.ม.(วิทยาการคอมพิวเตอร์) สถาบันบัณฑิตพัฒนบริหารศาสตร์",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "11",
    citizen_id: "3509900310152",
    name_title: "อ.",
    name_th: "อลงกต กองมณี",
    name_en: "Alongkot Gongmanee",
    position_academic: "อาจารย์",
    position_manager:
      "อาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
    image_profile: img_teacher_4,
    email: "alongkot@mju.ac.th",
    tel_number: "053-873890 ต่อ 22",
    education:
      "M.S.(Information Systems Management)  Ferris State University, U.S.A.",
    personnel_type: "อาจารย์",
    academic_type: "ข้าราชการ",
  },
  {
    id: "13",
    citizen_id: "3509900141059",
    name_title: "อ.ดร.",
    name_th: "กิตติกร หาญตระกูล",
    name_en: "Kittikorn Hantrakul",
    position_academic: "อาจารย์",
    position_manager:
      "ประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมเทคโนโลยีดิจิทัล, รองผู้อำนวยการสำนักบริหารและพัฒนาวิชาการ",
    image_profile: img_teacher_5,
    email: "kittikor@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 21",
    education: "ปร.ด.(การบริหารเทคโนโลยี) มหาวิทยาลัยแม่โจ้",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "14",
    citizen_id: "3520100840183",
    name_title: "อ.",
    name_th: "อรรถวิท ชังคมานนท์",
    name_en: "Attawit Changkamanon",
    position_academic: "อาจารย์",
    position_manager:
      "ประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
    image_profile: img_teacher_6,
    email: "attawit@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 13",
    education: "วท.ม.(วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "15",
    citizen_id: "1509900290333",
    name_title: "ผศ.",
    name_th: "ภานุวัฒน์ เมฆะ",
    name_en: "Panuwat Mekha",
    position_academic: "ผู้ช่วยศาสตราจารย์",
    position_manager:
      "รองประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
    image_profile: img_teacher_7,
    email: "panuwat_m@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 20",
    education: "วท.ม.(วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "61",
    citizen_id: "3529900125240",
    name_title: "ผศ.ดร.",
    name_th: "พาสน์ ปราโมกข์ชน",
    name_en: "Part Pramokchon",
    position_academic: "ผู้ช่วยศาสตราจารย์",
    position_manager:
      "เลขานุการอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมเทคโนโลยีดิจิทัล",
    image_profile: img_teacher_8,
    email: "part@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 16",
    education: "วศ.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "63",
    citizen_id: "3510600688933",
    name_title: "ผศ.ดร.",
    name_th: "ปวีณ เขื่อนแก้ว",
    name_en: "Paween Khoenkaw",
    position_academic: "ผู้ช่วยศาสตราจารย์",
    position_manager:
      "รองประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมเทคโนโลยีดิจิทัล",
    image_profile: img_teacher_9,
    email: "paween_k@mju.ac.th",
    tel_number: "053-873896",
    education: "วศ.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "64",
    citizen_id: "1509900130191",
    name_title: "อ.ดร.",
    name_th: "นษิ ตันติธารานุกุล",
    name_en: "Nasi Tantitharanukul",
    position_academic: "อาจารย์",
    position_manager: null,
    image_profile: img_teacher_10,
    email: "nasi@mju.ac.th",
    tel_number: "053-873890 ต่อ 19",
    education: "ปร.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "65",
    citizen_id: "3509900816561",
    name_title: "อ.ดร.",
    name_th: "กิติศักดิ์ โอสถานันต์กุล",
    name_en: "Kitisak Osathanunkul",
    position_academic: "อาจารย์",
    position_manager:
      "อาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
    image_profile: img_teacher_11,
    email: "kit_o@mju.ac.th",
    tel_number: "053-873897",
    education: "Ph.D.Computer Science, UK.",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
  {
    id: "66",
    citizen_id: "3501400030242",
    name_title: "อ.ดร.",
    name_th: "พยุงศักดิ์ เกษมสำราญ",
    name_en: "Payungsak Kasemsumran",
    position_academic: "อาจารย์",
    position_manager: null,
    image_profile: img_teacher_12,
    email: "payungsak_kae@mju.ac.th",
    tel_number: "053-873890-93 ต่อ 17",
    education: "ปร.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่",
    personnel_type: "อาจารย์",
    academic_type: "พนักงานมหาวิทยาลัย",
  },
];

export default teachers;
